CREATE DATABASE MindSet;

use MindSet;

CREATE TABLE Channels (
	`id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(500) NOT NULL UNIQUE,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Videos (
	`id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`link` VARCHAR(255) NOT NULL,
	`channel` VARCHAR(255) NOT NULL,
	`title` VARCHAR(255) NOT NULL,
	`duration` INT NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);